#!/usr/bin/env python3
"""audit.py — read the exported site back and check it against what it claims.

A passing build log is not verification: it only says the code ran. Every real defect
this site has shipped (the year 404 page telling Google to ignore it, www serving a
second copy of everything, one boilerplate description repeated 2,909 times) survived a
green build and was found by looking at the output. So this looks at the output.

Four things, all of them mechanical:

  1. TEXT. Every bullet rendered on a year, date or subject page is compared to the
     sentence in data/site that it was built from. The site's whole claim is that
     nothing was written or generated by us; if rendering ever alters a word, the claim
     is false. Bullets are read back out of the HTML, not out of the data.
  2. LINKS. Every internal href is resolved the way Cloudflare Pages resolves it (a bare
     file beats a directory index). The cross-cut pages drop anything under a thinness
     floor, so a link to a page that was never written is the easy mistake here.
  3. HEAD. Title, description and canonical must exist, be unique across the site, and
     the canonical must be the page's own URL. Duplicate descriptions were a real defect.
  4. ROBOTS. Nothing but the not-found page may carry noindex.

Exit code is non-zero if any check fails, so a deploy can be gated on it.

Usage:
  audit.py [--out site/out] [--site data/site] [--base https://slashyear.com]
           [--report audit.json]
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LI = re.compile(r'<li class="text-sm leading-relaxed text-foreground/85">(.*?)</li>', re.S)
TAG = re.compile(r"<[^>]+>")
TITLE = re.compile(r"<title>(.*?)</title>", re.S)
DESC = re.compile(r'<meta name="description" content="(.*?)"', re.S)
CANON = re.compile(r'<link rel="canonical" href="(.*?)"', re.S)
NOINDEX = re.compile(r'<meta name="robots" content="[^"]*noindex')
HREF = re.compile(r'href="(/[^"#?]*)"')


def flatten(fragment: str) -> str:
    """The visible words of one bullet: tags gone, entities decoded, the trailing
    'source' link dropped, whitespace normalised. The country chip (an /in/ link the
    page renders after a place row's sentence) is furniture, not sentence, and it is
    the only /in/ anchor a bullet can carry — drop it whole before untagging."""
    fragment = re.sub(r'<a[^>]*href="/in/[^"]*"[^>]*>.*?</a>', "", fragment, flags=re.S)
    text = html.unescape(TAG.sub("", fragment))
    text = re.sub(r"\s+", " ", text).strip()
    return text[:-6].strip() if text.endswith("source") else text


def url_of(path: str, out: str) -> str:
    rel = os.path.relpath(path, out).replace(os.sep, "/")
    if rel == "index.html":
        return "/"
    if rel == "404.html":
        return "__notfound__"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("/index.html")] + "/"
    return "/" + rel[: -len(".html")]


def servable(out: str) -> set[str]:
    """Every path Cloudflare Pages will answer, in its own resolution order: an exact
    file first, then <path>.html, then <path>/index.html."""
    paths: set[str] = set()
    for root, _dirs, files in os.walk(out):
        for f in files:
            rel = os.path.relpath(os.path.join(root, f), out).replace(os.sep, "/")
            paths.add("/" + rel)
            if rel.endswith(".html"):
                paths.add("/" + rel[: -len(".html")])
            if rel.endswith("/index.html"):
                paths.add("/" + rel[: -len("index.html")])
            if rel == "index.html":
                paths.add("/")
    return paths


def display(text: str) -> str:
    """The same shorthand expansion site/lib/display.ts applies at render time:
    "(b. 1473)" reads "(born 1473)", "(d. 275)" reads "(died 275)". The audit compares
    against what the reader sees, so the expectation must go through the same lens."""
    return re.sub(r"\((b|d)\.\s+(?=[^)\s])",
                  lambda m: "(born " if m.group(1) == "b" else "(died ", text)


def yearline(item: dict) -> str:
    """A cross-cut bullet reads "1066Edward the Confessor dies…" once the tags are gone:
    the year is its own element and the gap before the sentence is a CSS margin, not a
    space in the document. Comparing against a space here would fail all 655 of them."""
    return item["year_label"].removesuffix(" CE") + display(item["text"])


def expected_bullets(site: str) -> dict[str, list[str]]:
    """url -> the sentences that page must render, in order."""
    want: dict[str, list[str]] = {}
    for f in os.listdir(site):
        if not f.endswith(".json") or f == "index.json":
            continue
        page = json.load(open(os.path.join(site, f), encoding="utf-8"))
        url = "/404/" if page["year"] == 404 else f"/{page['year']}"
        want[url] = [display(i["text"]) for s in page["sections"] for i in s["items"]]

    dates = os.path.join(site, "dates")
    if os.path.isdir(dates):
        for f in os.listdir(dates):
            if f == "index.json" or not f.endswith(".json"):
                continue
            page = json.load(open(os.path.join(dates, f), encoding="utf-8"))
            want[f"/on/{page['slug']}"] = [
                yearline(i) for g in page["groups"] for i in g["items"]]

    ents = os.path.join(site, "entities")
    if os.path.isdir(ents):
        for f in os.listdir(ents):
            if f == "index.json" or not f.endswith(".json"):
                continue
            page = json.load(open(os.path.join(ents, f), encoding="utf-8"))
            want[f"/timeline/{page['slug']}"] = [yearline(i) for i in page["items"]]

    topic = os.path.join(site, "cross", "topic")
    if os.path.isdir(topic):
        for name in os.listdir(topic):
            d = os.path.join(topic, name)
            if not os.path.isdir(d):
                continue
            for f in os.listdir(d):
                page = json.load(open(os.path.join(d, f), encoding="utf-8"))
                want[f"/topic/{name}/{f[:-5]}"] = [yearline(i) for i in page["items"]]
    return want


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=os.path.join(ROOT, "site", "out"))
    ap.add_argument("--site", default=os.path.join(ROOT, "data", "site"))
    ap.add_argument("--base", default="https://slashyear.com")
    ap.add_argument("--report", default=os.path.join(ROOT, "audit.json"))
    a = ap.parse_args()
    base = a.base.rstrip("/")

    pages = [os.path.join(r, f) for r, _d, fs in os.walk(a.out) for f in fs if f.endswith(".html")]
    paths = servable(a.out)
    want = expected_bullets(a.site)

    fail: dict[str, list[str]] = defaultdict(list)
    titles: dict[str, str] = {}
    descs: dict[str, str] = {}
    checked_bullets = 0
    checked_links = 0

    for path in sorted(pages):
        url = url_of(path, a.out)
        doc = open(path, encoding="utf-8").read()

        if url == "/_not-found":
            continue  # a genuine Next internal: not linked from anywhere, not in the sitemap
        # /500 used to be skipped here as another "Next internal". It is not one: it is the
        # year page for 500 CE, it is linked from /499 and /501, and postbuild puts it in the
        # sitemap like every other year. The exemption is what let Next's noindex sit on a
        # published page unnoticed, so /500 is now audited exactly like /499.
        if url == "__notfound__":
            if not NOINDEX.search(doc):
                fail["robots"].append("404.html is missing noindex")
            continue

        # 1. text
        if url in want:
            got = [flatten(m) for m in LI.findall(doc)]
            exp = want[url]
            if got != exp:
                extra = [g for g in got if g not in exp][:2]
                missing = [e for e in exp if e not in got][:2]
                fail["text"].append(f"{url}: {len(got)} rendered vs {len(exp)} expected"
                                    + (f" | unexpected: {extra}" if extra else "")
                                    + (f" | missing: {missing}" if missing else ""))
            checked_bullets += len(exp)

        # 2. links
        for href in set(HREF.findall(doc)):
            checked_links += 1
            if href in paths or href.rstrip("/") + "/" in paths:
                continue
            fail["links"].append(f"{url} -> {href}")

        # 3. head
        t = TITLE.search(doc)
        d = DESC.search(doc)
        c = CANON.search(doc)
        if not t:
            fail["head"].append(f"{url}: no <title>")
        elif html.unescape(t.group(1)) in titles:
            fail["head"].append(f"{url}: title duplicates {titles[html.unescape(t.group(1))]}")
        else:
            titles[html.unescape(t.group(1))] = url
        if not d:
            fail["head"].append(f"{url}: no description")
        elif html.unescape(d.group(1)) in descs:
            fail["head"].append(f"{url}: description duplicates {descs[html.unescape(d.group(1))]}")
        else:
            descs[html.unescape(d.group(1))] = url
        if not c:
            fail["head"].append(f"{url}: no canonical")
        elif c.group(1).rstrip("/") != (base + url).rstrip("/"):
            fail["head"].append(f"{url}: canonical is {c.group(1)}")

        # 4. robots
        if NOINDEX.search(doc):
            fail["robots"].append(f"{url}: noindex on an indexable page")

    report = {
        "pages": len(pages),
        "bullets_checked": checked_bullets,
        "links_checked": checked_links,
        "failures": {k: v for k, v in fail.items()},
        "counts": {k: len(v) for k, v in fail.items()},
    }
    json.dump(report, open(a.report, "w", encoding="utf-8"), ensure_ascii=False, indent=1)

    print(f"audit: {len(pages)} pages, {checked_bullets:,} bullets, {checked_links:,} links")
    if not fail:
        print("  clean: text matches source, every internal link resolves, "
              "titles/descriptions/canonicals unique and correct, no stray noindex")
        return 0
    for k, v in fail.items():
        print(f"  {k}: {len(v)} failures")
        for line in v[:6]:
            print(f"    {line}")
    print(f"  full report: {a.report}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
