#!/usr/bin/env python3
"""verify.py — prove that every published sentence really is in the source it cites.

The site's whole claim is that nothing on it was written or generated by us, so that
claim has to be mechanically checkable rather than asserted. This walks the full chain
for every bullet on every page:

  1. published text  ==  clean_line(the stored wikitext line)   — nothing drifted in
                                                                  rendering
  2. that wikitext line is present verbatim in the stored article revision
  3. (--live) the stored revision is byte-identical to what Wikipedia serves for that
     revision id, so the local copy was not edited or corrupted

A failure at step 1 or 2 means a bullet exists that no source supports, which is the
one defect this site cannot ship with; the exit code is non-zero so a build can be
gated on it.

Usage:
  verify.py [--site data/site] [--claims data/claims] [--raw data/raw]
            [--live [--sample N]] [--report verification.json]
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import random
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract import OWN_DAY, clean_line, plausible_sources  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
API = "https://en.wikipedia.org/w/api.php"
UA = "slashyear-verify/1.0 (https://www.slashyear.com; ahmadopsr@gmail.com)"


def live_revision(revid: int) -> str | None:
    """Wikipedia throttles a burst of a few hundred requests, and a throttled fetch is
    not a mismatch — it is no answer. Retry with backoff and report the difference."""
    import time

    import requests
    s = requests.Session()
    s.headers["User-Agent"] = UA
    for attempt in range(5):
        try:
            r = s.get(API, params={"action": "parse", "oldid": revid, "prop": "wikitext",
                                   "format": "json", "formatversion": 2}, timeout=60)
            if r.status_code in (429, 503):
                time.sleep(2 ** attempt)
                continue
            r.raise_for_status()
            return r.json()["parse"]["wikitext"]
        except Exception:
            time.sleep(2 ** attempt)
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--site", default=os.path.join(ROOT, "data", "site"))
    ap.add_argument("--claims", default=os.path.join(ROOT, "data", "claims"))
    ap.add_argument("--raw", default=os.path.join(ROOT, "data", "raw"))
    ap.add_argument("--live", action="store_true",
                    help="also re-download each cited revision and compare it byte for byte")
    ap.add_argument("--sample", type=int, default=0,
                    help="with --live, check N random years instead of all of them")
    ap.add_argument("--report", default=os.path.join(ROOT, "verification.json"))
    a = ap.parse_args()

    pages = sorted((f for f in os.listdir(a.site) if f.endswith(".json") and f != "index.json"),
                   key=lambda f: int(f[:-5]))

    checked = rendered_ok = present_ok = 0
    failures: list[dict] = []
    lead_unsourced: list[int] = []

    for fn in pages:
        page = json.load(open(os.path.join(a.site, fn), encoding="utf-8"))
        # Step 0: the page is built from an article that really is about this year (or the
        # decade/century it sits in). Steps 1-3 below prove a sentence is in the article it
        # cites; they cannot notice that the article is about arithmetic rather than 2 CE.
        if page["source"]["title"] not in plausible_sources(page["year"]):
            failures.append({"year": page["year"], "stage": "source is not a year article",
                             "text": page["source"]["title"]})
        claims = json.load(open(os.path.join(a.claims, fn), encoding="utf-8"))["claims"]
        wikitext = json.load(open(os.path.join(a.raw, fn), encoding="utf-8"))["wikitext"]
        # From 1977 the deaths are not in the year article at all; deaths.py harvests
        # "Deaths in <month> <year>" and each of those claims carries its own source, so
        # the line has to be looked for in the revision it actually cites.
        extra_text: dict[int, str] = {}
        dpath = os.path.join(a.raw, "deaths", fn)
        if os.path.exists(dpath):
            for doc in json.load(open(dpath, encoding="utf-8"))["docs"]:
                extra_text[doc["source"]["revid"]] = doc["wikitext"]
        # Same again for the country-year articles places.py harvests: "1969 in Japan" is
        # a different article from "1969", and its rows cite its revision, so the line has
        # to be looked for there. Without this the check reports every country row as
        # "not in revision" -- 34,559 of them on the first run.
        for cpath in glob.glob(os.path.join(a.raw, "places", "*", fn)):
            doc = json.load(open(cpath, encoding="utf-8"))
            extra_text[doc["source"]["revid"]] = doc["wikitext"]
        by_text = {c["text"]: c for c in claims}

        for section in page["sections"]:
            for item in section["items"]:
                checked += 1
                claim = by_text.get(item["text"])
                if claim is None:
                    failures.append({"year": page["year"], "stage": "no source line",
                                     "text": item["text"][:160]})
                    continue
                redone, _links, ok = clean_line(claim["raw"])
                # Mirror extract.py exactly: a child that already opens with its own
                # day never had the parent's date prefixed (the 1934 two-dates rule),
                # even when older corpus rows still carry the unapplied `date_prefix`.
                if claim.get("date_prefix") and redone and not OWN_DAY.match(redone):
                    redone = f"{claim['date_prefix']} – {redone}"
                # A country-year article often writes the month once as ";February" and
                # then lists bare days under it, so the published sentence carries a month
                # the source line does not. Inserting it in front of the leading day number
                # is exactly reversible, which is the whole requirement here: the check is
                # still "re-derive the published text from the stored wikitext, mechanically".
                if claim.get("month_prefix") and redone:
                    redone = f"{claim['month_prefix']} {redone}"
                # The grouping header's context, appended by extract() the way the date
                # is prefixed — "— killed at the Battle of Flodden" on each of the
                # eleven people filed under that header. Equally reversible.
                if claim.get("context_suffix") and redone:
                    redone = f"{redone} — {claim['context_suffix']}"
                if ok and redone == item["text"]:
                    rendered_ok += 1
                else:
                    failures.append({"year": page["year"], "stage": "render drift",
                                     "published": item["text"][:160], "rederived": redone[:160]})
                    continue
                hay = extra_text.get((claim.get("source") or {}).get("revid"), wikitext)
                if claim["raw"] in hay:
                    present_ok += 1
                else:
                    failures.append({"year": page["year"], "stage": "not in revision",
                                     "text": item["text"][:160]})

        # The lead is a quotation too. When it was assembled from entries, every one of
        # them must be a bullet that appears on the same page.
        shown = {i["text"] for s in page["sections"] for i in s["items"]}
        if page["lead_from"] == "highest-ranked entries":
            if any(t not in shown for t in page.get("lead_items", [])):
                lead_unsourced.append(page["year"])

    print(f"bullets checked          : {checked}")
    print(f"  render matches source  : {rendered_ok}")
    print(f"  line present in revision: {present_ok}")
    print(f"  failures               : {len(failures)}")
    if lead_unsourced:
        print(f"  leads not traceable    : {len(lead_unsourced)} {lead_unsourced[:10]}")

    live_ok, live_bad, unreachable = 0, [], []
    jobs: list[tuple[int, int, str]] = []
    if a.live:
        import time
        years = [int(f[:-5]) for f in pages]
        if a.sample:
            random.seed(0)
            years = random.sample(years, min(a.sample, len(years)))
        print(f"\nre-downloading {len(years)} cited revisions ...")

        def check(job: tuple[int, int, str]):
            y, revid, stored = job
            fresh = live_revision(revid)
            if fresh is None:
                return y, revid, "unreachable"
            return y, revid, ("same" if fresh == stored else "differs")

        # Every revision the site cites, not just the year articles: the deaths lists are
        # cited on the page like anything else, so they get the same byte-for-byte proof.
        cited_revids: set[int] = set()
        for fn in pages:
            page = json.load(open(os.path.join(a.site, fn), encoding="utf-8"))
            for sec in page["sections"]:
                for it in sec["items"]:
                    cited_revids.add(it["cite"]["revid"])
        for y in years:
            rec = json.load(open(os.path.join(a.raw, f"{y}.json"), encoding="utf-8"))
            jobs.append((y, rec["source"]["revid"], rec["wikitext"]))
            dpath = os.path.join(a.raw, "deaths", f"{y}.json")
            if os.path.exists(dpath):
                for doc in json.load(open(dpath, encoding="utf-8"))["docs"]:
                    if doc["source"]["revid"] in cited_revids:
                        jobs.append((y, doc["source"]["revid"], doc["wikitext"]))
            for cpath in glob.glob(os.path.join(a.raw, "places", "*", f"{y}.json")):
                doc = json.load(open(cpath, encoding="utf-8"))
                if doc["source"]["revid"] in cited_revids:
                    jobs.append((y, doc["source"]["revid"], doc["wikitext"]))
        print(f"    ({len(jobs)} revisions in total)")

        by_revid = {j[1]: j for j in jobs}
        with ThreadPoolExecutor(max_workers=3) as ex:
            futs = [ex.submit(check, j) for j in jobs]
            for i, fut in enumerate(as_completed(futs), 1):
                y, revid, status = fut.result()
                if status == "same":
                    live_ok += 1
                elif status == "differs":
                    live_bad.append({"year": y, "revid": revid})
                else:
                    unreachable.append(by_revid[revid])
                if i % 200 == 0:
                    print(f"    {i}/{len(jobs)}", flush=True)
        # A throttled fetch is no answer, not a mismatch, and leaving it that way makes
        # the report read as incomplete coverage. Anything the parallel sweep could not
        # reach is retried one at a time, slowly, until Wikipedia answers.
        if unreachable:
            print(f"  retrying {len(unreachable)} throttled revisions serially ...", flush=True)
            still = []
            for job in unreachable:
                time.sleep(1.5)
                y, revid, status = check(job)
                if status == "same":
                    live_ok += 1
                elif status == "differs":
                    live_bad.append({"year": y, "revid": revid})
                else:
                    still.append(job)
            unreachable = still
        print(f"  revisions identical    : {live_ok}/{len(jobs)}")
        if unreachable:
            print("  unreachable (throttled): "
                  f"{len(unreachable)} {[(j[0], j[1]) for j in unreachable]}")
        if live_bad:
            print(f"  CONTENT DIFFERS        : {live_bad[:10]}")

    json.dump({"bullets": checked, "rendered_ok": rendered_ok, "present_ok": present_ok,
               "failures": failures[:200], "failure_count": len(failures),
               "leads_untraceable": lead_unsourced,
               "live_checked": live_ok, "live_bad": live_bad,
               "live_total": len(jobs) if a.live else len(pages), "live_unreachable": [(j[0], j[1]) for j in unreachable]},
              open(a.report, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"\nreport -> {a.report}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
